#ifndef APARTMENT_H
#define APARTMENT_H

#include "ResidentialBuilding.h"

/**
 * @class Apartment
 * @brief Represents an apartment, a specific type of residential building.
 * 
 * The Apartment class inherits from the ResidentialBuilding class and provides methods
 * for managing and retrieving various resource metrics specific to apartments.
 */
class Apartment : public ResidentialBuilding {
private:
    int satisfactionScore; ///< The satisfaction score of the apartment residents.
    int capacity;          ///< The capacity of the apartment (number of units or residents).
    int incomePerHour;    ///< The income generated by the apartment per hour.

public:
    /**
     * @brief Constructs an Apartment object with the specified ID.
     * @param id The unique ID of the apartment.
     */
    Apartment(int id);

    /**
     * @brief Destructor for the Apartment object.
     */
    ~Apartment();

    /**
     * @brief Prints the details of the apartment.
     */
    virtual void print() override;

    // New functions

    /**
     * @brief Gets the average satisfaction score for the apartment.
     * @return The average satisfaction score as a double.
     */
    double getAverageSatisfactionScore() override;

    /**
     * @brief Gets the total water supply for the apartment.
     * @return The total water supply.
     */
    int getTotalWaterSupply() override;

    /**
     * @brief Gets the total water usage of the apartment.
     * @return The total water usage.
     */
    int getTotalWaterUsage() override;

    /**
     * @brief Gets the total electricity supply for the apartment.
     * @return The total electricity supply.
     */
    int getTotalElectricitySupply() override;

    /**
     * @brief Gets the total electricity demand of the apartment.
     * @return The total electricity demand.
     */
    int getTotalElectricityDemand() override;

    /**
     * @brief Gets the total sewage capacity of the apartment.
     * @return The total sewage capacity.
     */
    int getTotalSewageCapacity() override;

    /**
     * @brief Gets the total waste capacity of the apartment.
     * @return The total waste capacity.
     */
    int getTotalWasteCapacity() override;

    /**
     * @brief Gets the total waste production of the apartment.
     * @return The total waste production.
     */
    int getTotalWasteProduction() override;

    /**
     * @brief Gets the total sewage production of the apartment.
     * @return The total sewage production.
     */
    int getTotalSewageProduction() override;

    /**
     * @brief Gets the total number of jobs provided by the apartment.
     * @return The total number of jobs.
     */
    int getTotalNumberOfJobs() override;
};

#endif // APARTMENT_H
