#ifndef TOWNHOUSE_H
#define TOWNHOUSE_H

#include "ResidentialBuilding.h"

/**
 * @class TownHouse
 * @brief Represents a townhouse, a type of residential building.
 * 
 * The TownHouse class inherits from the ResidentialBuilding class and includes
 * specific implementations for managing resources and calculating satisfaction scores.
 */
class TownHouse : public ResidentialBuilding {
private:
    int satisfactionScore; ///< The satisfaction score of the townhouse residents.
    int capacity;          ///< The capacity of the townhouse (number of residents or units).
    int incomePerHour;     ///< The income generated by the townhouse per hour.

public:
    /**
     * @brief Constructs a TownHouse object with a specified ID.
     * @param id The unique ID of the townhouse.
     */
    TownHouse(int id);

    /**
     * @brief Destructor for the TownHouse object.
     */
    ~TownHouse();

    /**
     * @brief Prints the details of the townhouse.
     */
    virtual void print() override;

    // New functions

    /**
     * @brief Gets the average satisfaction score for the townhouse.
     * @return The average satisfaction score as a double.
     */
    double getAverageSatisfactionScore() override;

    /**
     * @brief Gets the total water supply for the townhouse.
     * @return The total water supply.
     */
    int getTotalWaterSupply() override;

    /**
     * @brief Gets the total water usage of the townhouse.
     * @return The total water usage.
     */
    int getTotalWaterUsage() override;

    /**
     * @brief Gets the total electricity supply for the townhouse.
     * @return The total electricity supply.
     */
    int getTotalElectricitySupply() override;

    /**
     * @brief Gets the total electricity demand of the townhouse.
     * @return The total electricity demand.
     */
    int getTotalElectricityDemand() override;

    /**
     * @brief Gets the total sewage capacity of the townhouse.
     * @return The total sewage capacity.
     */
    int getTotalSewageCapacity() override;

    /**
     * @brief Gets the total waste capacity of the townhouse.
     * @return The total waste capacity.
     */
    int getTotalWasteCapacity() override;

    /**
     * @brief Gets the total waste production of the townhouse.
     * @return The total waste production.
     */
    int getTotalWasteProduction() override;

    /**
     * @brief Gets the total sewage production of the townhouse.
     * @return The total sewage production.
     */
    int getTotalSewageProduction() override;

    /**
     * @brief Gets the total number of jobs provided by the townhouse.
     * @return The total number of jobs.
     */
    int getTotalNumberOfJobs() override;
};

#endif // TOWNHOUSE_H
